# Generated by MathModel Skill scaffold generator.
from __future__ import annotations

import csv
import json
from pathlib import Path
import numpy as np
import pandas as pd
import openpyxl

from core_solver import simulate_fvm_fixed, sample_and_interpolate_fixed
from result_contract_io import (
    upsert_question_contracts,
    write_csv_table,
    table_entry,
    round_float,
    PROJECT_ROOT,
    OUTPUT_DIR,
    TABLES_DIR,
    RESULTS_DIR,
    DATA_CLEANED_DIR,
)

QUESTION = {
    'question_id': 'AQ1',
    'title': '预热平衡阶段温度与干基含水率',
    'task_type': '非线性扩散与热传导',
    'main_model': '隐式有限体积法 (FVM) + Picard迭代 + Thomas三对角求解',
}

def run_aq1():
    env_path = DATA_CLEANED_DIR / 'a_environment.csv'
    df_env = pd.read_csv(env_path)
    t_env = df_env['time_s'].values.astype(np.float64)
    T_env = df_env['temperature_K'].values.astype(np.float64)
    C_env = df_env['air_moisture_kgkg'].values.astype(np.float64)

    # 1. Run simulation for 1800 s with formula_mode=1 (Appendix 2)
    times_raw, T_raw, C_raw, end_time, n_rec = simulate_fvm_fixed(
        t_env=t_env,
        T_env=T_env,
        C_env=C_env,
        total_seconds=1800,
        formula_mode=1,
        sample_every_s=1,
        N=80,
        R=0.02,
        h=25.0,
        hm=8e-7,
        dt=1.0,
    )

    # 2. Build Table 1 (Temperature) & Table 2 (Moisture)
    times_tab = np.array([100, 300, 600, 900, 1200, 1500, 1800], dtype=np.float64)
    r_tab_cm = np.array([0.0, 0.5, 1.0, 1.5, 2.0], dtype=np.float64)

    # Interpolate to table points
    T_tab, C_tab = sample_and_interpolate_fixed(times_tab, T_raw[times_tab.astype(int)], C_raw[times_tab.astype(int)], N=80, R=0.02, r_target_cm=r_tab_cm)

    # Convert Temperature to Celsius
    T_tab_C = T_tab - 273.15

    # Write Table 1 CSV
    table1_rows = []
    for i, t_val in enumerate(times_tab):
        row = {'时间/s': int(t_val)}
        for j, r_val in enumerate(r_tab_cm):
            row[f'{r_val:g} cm'] = f'{T_tab_C[i, j]:.4f}'
        table1_rows.append(row)
    t1_path = TABLES_DIR / 'table_aq1_temperature.csv'
    write_csv_table(t1_path, table1_rows)

    # Write Table 2 CSV
    table2_rows = []
    for i, t_val in enumerate(times_tab):
        row = {'时间/s': int(t_val)}
        for j, r_val in enumerate(r_tab_cm):
            row[f'{r_val:g} cm'] = f'{C_tab[i, j]:.4f}'
        table2_rows.append(row)
    t2_path = TABLES_DIR / 'table_aq1_moisture.csv'
    write_csv_table(t2_path, table2_rows)

    # 3. Build result1.xlsx (1800 s, 0.1 cm steps)
    r_full_cm = np.arange(0.0, 2.0001, 0.1)
    T_full, C_full = sample_and_interpolate_fixed(times_raw, T_raw, C_raw, N=80, R=0.02, r_target_cm=r_full_cm)
    T_full_C = T_full - 273.15

    res1_path = TABLES_DIR / 'result1.xlsx'
    wb = openpyxl.Workbook(write_only=True)
    ws_T = wb.create_sheet('温度')
    ws_C = wb.create_sheet('水分浓度')

    header = ['时间\\到药材中心的距离'] + [round(r, 1) for r in r_full_cm]
    ws_T.append(header)
    ws_C.append(header)

    # 1 to 1800 s
    for s in range(1, 1801):
        row_T = [s] + [round(val, 4) for val in T_full_C[s]]
        row_C = [s] + [round(val, 4) for val in C_full[s]]
        ws_T.append(row_T)
        ws_C.append(row_C)
    wb.save(res1_path)

    # 4. Metrics & Contracts
    metrics = [
        {'metric_name': 'aq1_final_center_temperature_C', 'metric_role': 'evaluation', 'value': round_float(T_full_C[1800, 0], 4), 'unit': '°C'},
        {'metric_name': 'aq1_final_surface_temperature_C', 'metric_role': 'evaluation', 'value': round_float(T_full_C[1800, -1], 4), 'unit': '°C'},
        {'metric_name': 'aq1_final_center_moisture', 'metric_role': 'evaluation', 'value': round_float(C_full[1800, 0], 4), 'unit': 'kg/kg'},
        {'metric_name': 'aq1_final_surface_moisture', 'metric_role': 'evaluation', 'value': round_float(C_full[1800, -1], 4), 'unit': 'kg/kg'},
        {'metric_name': 'aq1_total_moisture_loss_fraction', 'metric_role': 'evaluation', 'value': round_float((2.55 - np.mean(C_full[1800])) / 2.55, 6), 'unit': 'fraction'},
    ]

    conclusions = [
        {
            'question_id': 'AQ1',
            'conclusion_text': f'在预热平衡阶段（0-1800 s），药材受烘房升温与对流传热驱动，中心温度由28.0000°C上升至{T_full_C[1800, 0]:.4f}°C，表面温度达到{T_full_C[1800, -1]:.4f}°C；由于对流传质阻力与内部非线性水分扩散制约，药材表面干基含水率由2.5500 kg/kg下降至{C_full[1800, -1]:.4f} kg/kg，中心干基含水率为{C_full[1800, 0]:.4f} kg/kg，体现出显著的内外梯度迟滞效应。',
            'evidence_required': ['model_results.json', 'metrics.json', 'table_index.json'],
            'evidence_status': 'computed',
        }
    ]

    tables = [
        table_entry(
            question_id='AQ1',
            table_id='table1',
            title='30分钟内药材的温度（表1）',
            purpose='展示预热阶段100-1800 s各径向截面的药材温度动态。',
            path=t1_path,
            status='computed',
        ),
        table_entry(
            question_id='AQ1',
            table_id='table2',
            title='30分钟内药材的水分浓度（表2）',
            purpose='展示预热阶段100-1800 s各径向截面的干基水分浓度分布。',
            path=t2_path,
            status='computed',
        ),
    ]

    outputs = [
        {'path': str(t1_path), 'type': 'csv'},
        {'path': str(t2_path), 'type': 'csv'},
        {'path': str(res1_path), 'type': 'xlsx'},
    ]

    summary = f'AQ1预热平衡阶段数值求解完成：1800 s时中心温度为{T_full_C[1800, 0]:.4f}°C，表面温度为{T_full_C[1800, -1]:.4f}°C；中心水分浓度为{C_full[1800, 0]:.4f} kg/kg，表面水分浓度为{C_full[1800, -1]:.4f} kg/kg。表1、表2及result1.xlsx均已导出。'

    upsert_question_contracts(
        question=QUESTION,
        result_summary=summary,
        metrics=metrics,
        tables=tables,
        conclusions=conclusions,
        outputs=outputs,
        status='computed',
    )
    print('AQ1 finished successfully.')

if __name__ == '__main__':
    run_aq1()
