# Generated by MathModel Skill scaffold generator.
from __future__ import annotations

import hashlib
import json
import os
import platform
import subprocess
import sys
from datetime import datetime
from pathlib import Path


THIS_DIR = Path(__file__).resolve().parent


def detect_project_root() -> Path:
    for parent in THIS_DIR.parents:
        if parent.name == "paper_output":
            return parent.parent
    return Path.cwd().resolve()


PROJECT_ROOT = detect_project_root()
OUTPUT_DIR = PROJECT_ROOT / "paper_output"
RESULTS_DIR = OUTPUT_DIR / "results"
DATA_CLEANED_DIR = OUTPUT_DIR / "data_cleaned"
MODEL_RESULTS_FILE = RESULTS_DIR / "model_results.json"
RUN_MANIFEST_FILE = RESULTS_DIR / "run_manifest.json"


def configure_utf8_stdio() -> None:
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            pass


def safe_print(text: object = "", *, end: str = "\n") -> None:
    message = str(text)
    try:
        print(message, end=end)
    except UnicodeEncodeError:
        encoding = getattr(sys.stdout, "encoding", None) or "utf-8"
        safe = message.encode(encoding, errors="replace").decode(encoding, errors="replace")
        print(safe, end=end)


def now() -> str:
    return datetime.now().isoformat(timespec="seconds")


def rel(path: Path) -> str:
    try:
        return path.resolve().relative_to(PROJECT_ROOT).as_posix()
    except Exception:
        return str(path).replace("\\", "/")


def resolve(path_text: object) -> Path:
    path = Path(str(path_text or "").strip())
    if path.is_absolute():
        return path
    return PROJECT_ROOT / path


def load_json(path: Path, default):
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return default


def sha256(path: Path) -> str:
    if not path.exists() or not path.is_file():
        return ""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def input_file_entries() -> list[dict[str, str]]:
    if not DATA_CLEANED_DIR.exists():
        return []
    entries = []
    for path in sorted(item for item in DATA_CLEANED_DIR.rglob("*") if item.is_file()):
        entries.append({"path": rel(path), "bytes": path.stat().st_size, "sha256": sha256(path)})
    return entries


def normalize_path(path_text: object) -> str:
    if not path_text:
        return ""
    return rel(resolve(path_text))


def provenance_for_script(script: Path) -> tuple[list[str], list[str]]:
    data = load_json(MODEL_RESULTS_FILE, {})
    questions = data.get("questions") if isinstance(data, dict) else []
    qids: list[str] = []
    artifacts: list[str] = []
    script_rel = rel(script)
    if not isinstance(questions, list):
        return qids, artifacts
    for item in questions:
        if not isinstance(item, dict):
            continue
        provenance = item.get("execution_provenance")
        if not isinstance(provenance, dict):
            continue
        if normalize_path(provenance.get("source_code_path")) != script_rel:
            continue
        qid = str(item.get("question_id") or "").strip()
        if qid:
            qids.append(qid)
        for artifact in provenance.get("output_artifacts", []) or []:
            path_text = str(artifact)
            if path_text and path_text not in artifacts:
                artifacts.append(path_text)
    return qids, artifacts


def artifact_entries(paths: list[str]) -> list[dict[str, object]]:
    entries = []
    for path_text in paths:
        path = resolve(path_text)
        entries.append(
            {
                "path": normalize_path(path_text),
                "exists": path.exists(),
                "bytes": path.stat().st_size if path.exists() and path.is_file() else 0,
                "sha256": sha256(path),
            }
        )
    return entries


def write_run_manifest(runs: list[dict[str, object]]) -> None:
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    manifest = {
        "schema_version": "1.0",
        "generated_by": "paper_output/code/modeling/run_modeling.py",
        "generated_at": now(),
        "status": "PASS" if all(item.get("returncode") == 0 for item in runs) else "FAIL",
        "runs": runs,
    }
    RUN_MANIFEST_FILE.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")


def main() -> int:
    configure_utf8_stdio()
    scripts = sorted(path for path in THIS_DIR.glob("q*_model.py") if path.name[:1].lower() == "q")
    if not scripts:
        safe_print("No q*_model.py scripts found.")
        write_run_manifest([])
        return 0
    failures = 0
    runs: list[dict[str, object]] = []
    for script in scripts:
        safe_print(f"=== Running {script.name} ===")
        started_at = now()
        command = [sys.executable, str(script)]
        env = dict(os.environ)
        env["PYTHONIOENCODING"] = "utf-8"
        result = subprocess.run(
            command,
            cwd=str(THIS_DIR),
            env=env,
            text=True,
            encoding="utf-8",
            errors="replace",
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            check=False,
        )
        if result.stdout:
            safe_print(result.stdout, end="" if result.stdout.endswith("\n") else "\n")
        if result.returncode != 0:
            failures += 1
            safe_print(f"[warning] {script.name} exited with code {result.returncode}")
        qids, artifacts = provenance_for_script(script)
        runs.append(
            {
                "run_id": f"{script.stem}_{started_at.replace(':', '').replace('-', '').replace('T', '_')}",
                "script": rel(script),
                "script_sha256": sha256(script),
                "question_ids": qids,
                "command": " ".join(command),
                "returncode": result.returncode,
                "status": "PASS" if result.returncode == 0 else "FAIL",
                "started_at": started_at,
                "finished_at": now(),
                "working_directory": rel(THIS_DIR),
                "environment": {
                    "python": sys.version.split()[0],
                    "implementation": platform.python_implementation(),
                    "platform": platform.platform(),
                },
                "input_files": input_file_entries(),
                "output_artifacts": artifact_entries(artifacts),
                "stdout_tail": (result.stdout or "")[-4000:],
            }
        )
    write_run_manifest(runs)
    safe_print(f"Run manifest written: {RUN_MANIFEST_FILE}")
    if failures:
        safe_print(f"Completed with {failures} failed modeling script(s).")
        return 1
    safe_print("All modeling scaffold scripts completed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
